import type { Metadata } from "next";
import "./globals.css";
import { Inter, Lora, Roboto_Mono } from "next/font/google"
import { cn } from "@/lib/utils"
import { SiteNavbar } from "@/components/navbar";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek', 'greek-ext', 'vietnamese'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], variable: '--font-inter' });

const lora = Lora({ subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'math', 'symbols', 'vietnamese'], weight: ['400', '500', '600', '700'], variable: '--font-lora' });

const robotoMono = Roboto_Mono({ subsets: ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek', 'vietnamese'], weight: ['100', '200', '300', '400', '500', '600', '700'], variable: '--font-roboto-mono' });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.variable, lora.variable, robotoMono.variable)}
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning
      >
        <Analytics />
        <SiteNavbar />
        {children}
      </body>
    </html>
  );
}
